[package]
name = "mini_invoice"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.52.1", features = ["full"]}
axum = {version = "0.8.9"}
sea-orm = {version = "2.0.0-rc.38", features = ["macros", "sqlx-postgres","runtime-tokio-native-tls", "debug-print", "schema-sync", "entity-registry"]}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = {version = "1.0.149"}
dotenvy = {version = "0.15.7"}
thiserror = {version = "2.0.18"}
anyhow = {version = "1.0.102"}
tracing = {version = "0.1.44"}
chrono = {version = "0.4.44", features = ["serde"]}
validator = {version = "0.20.0", features = ["derive"]}
jsonwebtoken = {version = "10.3.0", features =["rust_crypto"]}
config = "0.15.22"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
nanoid="0.5.0"
tower-http = {version = "0.6.8", features = ["cors", "trace"]}
argon2 = {version = "0.6.0-rc.8", features = ["rand_core","getrandom"]}
axum-extra = {version = "0.12.6", features = ["query"]}
aide = {version = "0.15.1", features = ["axum", "axum-json", "axum-query", "swagger"]}
schemars = {version = "0.9.0", features = ["rust_decimal1"]}
